export const SDG_list = [
  { sdgId: 1, value: "No Poverty", label: "1. No Poverty", color: "#f23" },
  { sdgId: 2, value: "Zero Hunger", label: "2. Zero Hunger", color: "#da3" },
  {
    sdgId: 3,
    value: "Good Health and Well-Being",
    label: "3. Good Health and Well-Being",
    color: "#ad2",
  },
  {
    sdgId: 4,
    value: "Quality Education",
    label: "4. Quality Education",
    color: "#c23",
  },
  {
    sdgId: 5,
    value: "Gender Equality",
    label: "5. Gender Equality",
    color: "#f43",
  },
  {
    sdgId: 6,
    value: "Clean Water and Sanitation",
    label: "6. Clean Water and Sanitation",
    color: "#0be",
  },
  {
    sdgId: 7,
    value: "Affordable and Clean Energy",
    label: "7. Affordable and Clean Energy",
    color: "#fb1",
  },
  {
    sdgId: 8,
    value: "Decent Work and Economic Growth",
    label: "8. Decent Work and Economic Growth",
    color: "#924",
  },
  {
    sdgId: 9,
    value: "Industry, Innovation and Infrastructure",
    label: "9. Industry, Innovation and Infrastructure",
    color: "#f73",
  },
  {
    sdgId: 10,
    value: "Reduced Inequalities",
    label: "10. Reduced Inequalities",
    color: "#e16",
  },
  {
    sdgId: 11,
    value: "Sustainable Cities and Communities",
    label: "11. Sustainable Cities and Communities",
    color: "#fa2",
  },
  {
    sdgId: 12,
    value: "Responsible Consumption and Production",
    label: "12. Responsible Consumption and Production",
    color: "#d93",
  },
  {
    sdgId: 13,
    value: "Climate Action",
    label: "13. Climate Action",
    color: "#574",
  },
  {
    sdgId: 14,
    value: "Life Below Water",
    label: "14. Life Below Water",
    color: "#08c",
  },
  {
    sdgId: 15,
    value: "Life On Land",
    label: "15. Life On Land",
    color: "#4b5",
  },
  {
    sdgId: 16,
    value: "Peace, Justice and Strong Institutions",
    label: "16. Peace, Justice and Strong Institutions",
    color: "#059",
  },
  {
    sdgId: 17,
    value: "Partnerships For The Goals",
    label: "17. Partnerships For The Goals",
    color: "#059",
  },
];
